apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapps
spec:
  replicas: 1
  selector:
    matchLabels:
      ntuc-k8s: hw3
  template:
    metadata:
      labels:
        ntuc-k8s: hw3
    spec:
      serviceAccountName: dm-incluster
      containers:
        - name: newapps
          image: acs107120/incluster:latest
          imagePullPolicy: IfNotPresent           
